apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-guestbook-secrets
spec:
  secretStoreRef:
    name: aws-secrets-manager-store
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-guestbook-secrets
    deletionPolicy: Delete
  data:
    - secretKey: MYSQL_USER_PASSWORD
      remoteRef:
        key: guestbook/passwords
        property: mysql_user_password
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: guestbook/passwords
        property: mysql_root_password
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: guestbook/passwords
        property: redis_password